/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.MediaTracker;

/**
 *
 * @author dylan
 */
public class GUI_VerCartones extends javax.swing.JFrame {

    /**
     * Creates new form GUI_VerCartones
     */
    public GUI_VerCartones() {
        initComponents();
        setLocationRelativeTo(null);
        
        btn_Consultar.addActionListener((java.awt.event.ActionEvent evt) -> {
            String identificador = jtf_Identificador.getText().trim();
            if (!identificador.isEmpty()) {
                mostrarCarton(identificador);
            }
        });    
        
    }
    
    private void mostrarCarton(String identificador) {
        String rutaImagen = "src/main/java/modelo/Cartones/Imagenes/" + identificador + ".png";
        ImageIcon image = new ImageIcon(rutaImagen);
       
        if (image.getImageLoadStatus() == MediaTracker.ERRORED) {
            // Si la imagen no existe
            JOptionPane.showMessageDialog(this, "No se ha encontrado algún cartón de bingo con el identificador: " + identificador, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Si la imagen existe
            Icon icon = new ImageIcon(image.getImage().getScaledInstance(jl_Carton.getWidth(), jl_Carton.getHeight(), Image.SCALE_DEFAULT));
            jl_Carton.setIcon(icon);
            this.repaint();
        }
    }        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_Encabezado = new javax.swing.JPanel();
        jl_Titulo = new javax.swing.JLabel();
        jl_Identificador = new javax.swing.JLabel();
        jtf_Identificador = new javax.swing.JTextField();
        btn_Consultar = new javax.swing.JButton();
        jp_Cuerpo = new javax.swing.JPanel();
        jp_Carton = new javax.swing.JPanel();
        jl_Carton = new javax.swing.JLabel();

        jp_Encabezado.setBackground(new java.awt.Color(255, 255, 255));

        jl_Titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jl_Titulo.setText("Consultar cartón");

        jl_Identificador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_Identificador.setText("Identificador:");

        btn_Consultar.setText("Consultar");

        javax.swing.GroupLayout jp_EncabezadoLayout = new javax.swing.GroupLayout(jp_Encabezado);
        jp_Encabezado.setLayout(jp_EncabezadoLayout);
        jp_EncabezadoLayout.setHorizontalGroup(
            jp_EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_EncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_Titulo)
                .addGap(18, 18, 18)
                .addComponent(jl_Identificador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_Identificador)
                .addGap(18, 18, 18)
                .addComponent(btn_Consultar)
                .addGap(19, 19, 19))
        );
        jp_EncabezadoLayout.setVerticalGroup(
            jp_EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_EncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Titulo)
                    .addComponent(jl_Identificador)
                    .addComponent(jtf_Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Consultar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_Cuerpo.setBackground(new java.awt.Color(204, 204, 255));

        jp_Carton.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp_CartonLayout = new javax.swing.GroupLayout(jp_Carton);
        jp_Carton.setLayout(jp_CartonLayout);
        jp_CartonLayout.setHorizontalGroup(
            jp_CartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_CartonLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jl_Carton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jp_CartonLayout.setVerticalGroup(
            jp_CartonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_CartonLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jl_Carton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_CuerpoLayout = new javax.swing.GroupLayout(jp_Cuerpo);
        jp_Cuerpo.setLayout(jp_CuerpoLayout);
        jp_CuerpoLayout.setHorizontalGroup(
            jp_CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_CuerpoLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jp_Carton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jp_CuerpoLayout.setVerticalGroup(
            jp_CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_CuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Carton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_Cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_Cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_VerCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_VerCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_VerCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_VerCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_VerCartones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Consultar;
    private javax.swing.JLabel jl_Carton;
    private javax.swing.JLabel jl_Identificador;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JPanel jp_Carton;
    private javax.swing.JPanel jp_Cuerpo;
    private javax.swing.JPanel jp_Encabezado;
    private javax.swing.JTextField jtf_Identificador;
    // End of variables declaration//GEN-END:variables
}
