/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import modelo.CartonBingo;

/**
 *
 * @author dylan
 */
public class GUI_CrearCartones extends javax.swing.JFrame {
    private static GUI_CrearCartones instance;
    private ArrayList<CartonBingo> cartonesGenerados = new ArrayList<>();
    /**
     * Creates new form GUI_CrearCartones
     */
    public GUI_CrearCartones() {
        initComponents();
        setLocationRelativeTo(null);
        
        // Agregar un manejador de eventos al botón "Generar"
        btn_Generar.addActionListener((java.awt.event.ActionEvent evt) -> {
            int cantidadCartones = (int) js_Cantidad.getValue(); // Obtener la cantidad de cartones deseada
            generarCartones(cantidadCartones);
        });
    }

    public static GUI_CrearCartones getInstance() {
        if (instance == null) {
            instance = new GUI_CrearCartones();
        }
        return instance;
    }    
    
    // Método para generar la cantidad de cartones deseada
    private void generarCartones(int cantidadCartones) {
        String rutaCarpeta = "src/main/java/modelo/Cartones/Imagenes/";
        limpiarCarpeta(rutaCarpeta);  
        
        for (int i = 0; i < cantidadCartones; i++) {            
            CartonBingo carton = new CartonBingo();
            cartonesGenerados.add(carton);         
            
            // Imprimir el identificador del cartón
            System.out.println("Identificador del Cartón " + (i + 1) + ": " + carton.getIdentificador());
            // Imprimir la matriz de números del cartón
            int[][] matrizNumeros = carton.getMatrizNumeros();
            for (int[] matrizNumero : matrizNumeros) {
                for (int k = 0; k < matrizNumero.length; k++) {
                    System.out.print(matrizNumero[k] + "\t");
                }
                System.out.println(); // Nueva línea para la siguiente fila
            }
            System.out.println();
        }
        
        for (CartonBingo carton : cartonesGenerados) {
            System.out.println("Identificador del Cartón: " + carton.getIdentificador() + ", Matriz: " + Arrays.toString(carton.getMatrizNumeros()));
        }            
        
// Mostrar una ventana emergente con información
        JOptionPane.showMessageDialog(this, cantidadCartones + " cartones creados con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        // Cerrar el JFrame
        this.setVisible(false);        
    }   

    public void limpiarCarpeta(String rutaCarpeta) {
        File carpeta = new File(rutaCarpeta);

        if (carpeta.exists() && carpeta.isDirectory()) {
            File[] archivos = carpeta.listFiles();

            if (archivos != null) {
                for (File archivo : archivos) {
                    if (archivo.isDirectory()) {
                        // Si es un directorio, llamar recursivamente para eliminar su contenido
                        limpiarCarpeta(archivo.getAbsolutePath());
                    }
                    archivo.delete();
                }
            }
        } 
    }    

    public ArrayList<CartonBingo> getCartonesGenerados() {
        return cartonesGenerados;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_Cantidad = new javax.swing.JLabel();
        js_Cantidad = new javax.swing.JSpinner();
        btn_Generar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jl_Titulo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jl_Cantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_Cantidad.setText("Cantidad:");

        js_Cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));
        js_Cantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        js_Cantidad.setFocusCycleRoot(true);

        btn_Generar.setText("Generar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jl_Cantidad)
                .addGap(18, 18, 18)
                .addComponent(js_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_Generar)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Cantidad)
                    .addComponent(js_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Generar))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jl_Titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jl_Titulo.setText("Generar Cartones de Bingo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jl_Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_CrearCartones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Generar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jl_Cantidad;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JSpinner js_Cantidad;
    // End of variables declaration//GEN-END:variables
}
