/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Dimension;
import static javax.swing.JList.VERTICAL;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author edurg
 */
public class GUI_Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Estadisticas
     */
    public GUI_Estadisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Generar estadistica");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Estadisticas de las partidas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jButton2.setText("Generar estadistica");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Modos mas jugados");

        jLabel3.setText("Numeros mas frecuentes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            // Crear el conjunto de datos
    DefaultPieDataset dataset = new DefaultPieDataset();
    dataset.setValue("Character 1", 10);
    dataset.setValue("Character 2", 15);
    dataset.setValue("Character 3", 20);
    dataset.setValue("Character 4", 30);

    // Crear el gráfico
    JFreeChart pieChart = ChartFactory.createPieChart(
        "Top 4 Characters",
        dataset,
        true, 
        true,
        false
    );

    // Crear el panel del gráfico y añadirlo al jPanel1
    ChartPanel chartPanel = new ChartPanel(pieChart);
    jPanel1.setLayout(new java.awt.BorderLayout());
    jPanel1.add(chartPanel, BorderLayout.CENTER);
    jPanel1.validate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // TODO add your handling code here:
      /*
      int num1 = 10;
      int num2 = 10;
      int num3 = 30;
      int num4 = 12;
      int num5 = 34;
      int num6 = 1;
      int num7 = 4;
      int num8 = 7;
      int num9 = 13;
      int num10 = 11;
      
      //DefaultCategoryDatSet datos = new DefaultCategoryDatSet();
      DefaultCategoryDataset datos = new DefaultCategoryDataset();
      
      datos.setValue(num3,"Numero mas salido", null );
      datos.setValue(num1,"Numero mas salido", null );
      datos.setValue(num2,"Numero mas salido", null );
      datos.setValue(num4,"Numero mas salido", null );
      datos.setValue(num5,"Numero mas salido", null );
      datos.setValue(num6,"Numero mas salido", null );
      datos.setValue(num7,"Numero mas salido", null );
      datos.setValue(num8,"Numero mas salido", null );
      datos.setValue(num9,"Numero mas salido", null );
      datos.setValue(num10,"Numero mas salido", null );
      //datos.setValue(num3,"Numero mas salido", null );
      
      JFreeChart graficoMayor =  ChartFactory.createBarChart(
        "Numeros mas recurrentes jugados",
        "Numeros:", 
        "Repeticiones:",
        datos,
        PlotOrientation.VERTICAL,
        true,
        true,
        false
      ); 
      
      
      
     ChartPanel panel1 = new ChartPanel(graficoMayor);
     panel1.setMouseWheelEnabled(true);
     panel1.setPreferredSize(new Dimension(400,200));
     jPanel1.setLayout(new BorderLayout());
     jPanel1.add(panel1, BorderLayout.NORTH);
     
     pack();
     repaint();
     
     */ 
      // Crear el conjunto de datos
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    dataset.addValue(10, "Number", "1");
    dataset.addValue(10, "Number", "2");
    dataset.addValue(30, "Number", "3");
    dataset.addValue(12, "Number", "4");
    dataset.addValue(34, "Number", "5");
    dataset.addValue(1, "Number", "6");
    dataset.addValue(4, "Number", "7");
    dataset.addValue(7, "Number", "8");
    dataset.addValue(13, "Number", "9");
    dataset.addValue(11, "Number", "10");

    // Crear el gráfico
    JFreeChart barChart = ChartFactory.createBarChart(
        "Top 10 Numbers",
        "Number",
        "Count",
        dataset
    );

    // Crear el panel del gráfico y añadirlo al jPanel1
    ChartPanel chartPanel = new ChartPanel(barChart);
    jPanel1.setLayout(new java.awt.BorderLayout());
    jPanel1.add(chartPanel, BorderLayout.CENTER);
    jPanel1.validate();

            
      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
